//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 02:59:01 PM GMT 
//

package uk.ac.liv.mzqlib.openms.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the uk.ac.liv.mzqlib.openms.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: uk.ac.liv.mzqlib.openms.jaxb
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsensusElement }
     *
     */
    public ConsensusElement createConsensusElement() {
        return new ConsensusElement();
    }

    /**
     * Create an instance of {@link ConsensusXML }
     *
     */
    public ConsensusXML createConsensusXML() {
        return new ConsensusXML();
    }

    /**
     * Create an instance of {@link ConsensusXML.UnassignedPeptideIdentification
     * }
     *
     */
    public ConsensusXML.UnassignedPeptideIdentification createConsensusXMLUnassignedPeptideIdentification() {
        return new ConsensusXML.UnassignedPeptideIdentification();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun }
     *
     */
    public ConsensusXML.IdentificationRun createConsensusXMLIdentificationRun() {
        return new ConsensusXML.IdentificationRun();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.ProteinIdentification
     * }
     *
     */
    public ConsensusXML.IdentificationRun.ProteinIdentification createConsensusXMLIdentificationRunProteinIdentification() {
        return new ConsensusXML.IdentificationRun.ProteinIdentification();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.SearchParameters
     * }
     *
     */
    public ConsensusXML.IdentificationRun.SearchParameters createConsensusXMLIdentificationRunSearchParameters() {
        return new ConsensusXML.IdentificationRun.SearchParameters();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing }
     *
     */
    public ConsensusXML.DataProcessing createConsensusXMLDataProcessing() {
        return new ConsensusXML.DataProcessing();
    }

    /**
     * Create an instance of {@link ConsensusElement.PeptideIdentification }
     *
     */
    public ConsensusElement.PeptideIdentification createConsensusElementPeptideIdentification() {
        return new ConsensusElement.PeptideIdentification();
    }

    /**
     * Create an instance of {@link Centroid }
     *
     */
    public Centroid createCentroid() {
        return new Centroid();
    }

    /**
     * Create an instance of {@link GroupedElementList }
     *
     */
    public GroupedElementList createGroupedElementList() {
        return new GroupedElementList();
    }

    /**
     * Create an instance of {@link Element }
     *
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link uk.ac.liv.mzqlib.openms.jaxb.UserParam }
     *
     */
    public uk.ac.liv.mzqlib.openms.jaxb.UserParam createUserParam() {
        return new uk.ac.liv.mzqlib.openms.jaxb.UserParam();
    }

    /**
     * Create an instance of {@link ConsensusElementList }
     *
     */
    public ConsensusElementList createConsensusElementList() {
        return new ConsensusElementList();
    }

    /**
     * Create an instance of {@link MapList }
     *
     */
    public MapList createMapList() {
        return new MapList();
    }

    /**
     * Create an instance of {@link Map }
     *
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link ConsensusXML.UnassignedPeptideIdentification.PeptideHit
     * }
     *
     */
    public ConsensusXML.UnassignedPeptideIdentification.PeptideHit createConsensusXMLUnassignedPeptideIdentificationPeptideHit() {
        return new ConsensusXML.UnassignedPeptideIdentification.PeptideHit();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit
     * }
     *
     */
    public ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit createConsensusXMLIdentificationRunProteinIdentificationProteinHit() {
        return new ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.SearchParameters.FixedModification
     * }
     *
     */
    public ConsensusXML.IdentificationRun.SearchParameters.FixedModification createConsensusXMLIdentificationRunSearchParametersFixedModification() {
        return new ConsensusXML.IdentificationRun.SearchParameters.FixedModification();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.SearchParameters.VariableModification
     * }
     *
     */
    public ConsensusXML.IdentificationRun.SearchParameters.VariableModification createConsensusXMLIdentificationRunSearchParametersVariableModification() {
        return new ConsensusXML.IdentificationRun.SearchParameters.VariableModification();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing.Software }
     *
     */
    public ConsensusXML.DataProcessing.Software createConsensusXMLDataProcessingSoftware() {
        return new ConsensusXML.DataProcessing.Software();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing.ProcessingAction
     * }
     *
     */
    public ConsensusXML.DataProcessing.ProcessingAction createConsensusXMLDataProcessingProcessingAction() {
        return new ConsensusXML.DataProcessing.ProcessingAction();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing.UserParam }
     *
     */
    public ConsensusXML.DataProcessing.UserParam createConsensusXMLDataProcessingUserParam() {
        return new ConsensusXML.DataProcessing.UserParam();
    }

    /**
     * Create an instance of {@link ConsensusElement.PeptideIdentification.PeptideHit
     * }
     *
     */
    public ConsensusElement.PeptideIdentification.PeptideHit createConsensusElementPeptideIdentificationPeptideHit() {
        return new ConsensusElement.PeptideIdentification.PeptideHit();
    }

    /**
     * Create an instance of {@link FeatureMap }
     *
     */
    public FeatureMap createFeatureMap() {
        return new FeatureMap();
    }

    /**
     * Create an instance of {@link FeatureType }
     *
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link FeatureType.PeptideIdentification }
     *
     */
    public FeatureType.PeptideIdentification createFeatureTypePeptideIdentification() {
        return new FeatureType.PeptideIdentification();
    }

    /**
     * Create an instance of {@link FeatureType.Convexhull }
     *
     */
    public FeatureType.Convexhull createFeatureTypeConvexhull() {
        return new FeatureType.Convexhull();
    }

    /**
     * Create an instance of {@link FeatureType.Convexhull.Hullpoint }
     *
     */
    public FeatureType.Convexhull.Hullpoint createFeatureTypeConvexhullHullpoint() {
        return new FeatureType.Convexhull.Hullpoint();
    }

    /**
     * Create an instance of {@link FeatureType.Model }
     *
     */
    public FeatureType.Model createFeatureTypeModel() {
        return new FeatureType.Model();
    }

    /**
     * Create an instance of {@link FeatureMap.UnassignedPeptideIdentification }
     *
     */
    public FeatureMap.UnassignedPeptideIdentification createFeatureMapUnassignedPeptideIdentification() {
        return new FeatureMap.UnassignedPeptideIdentification();
    }

    /**
     * Create an instance of {@link FeatureMap.IdentificationRun }
     *
     */
    public FeatureMap.IdentificationRun createFeatureMapIdentificationRun() {
        return new FeatureMap.IdentificationRun();
    }

    /**
     * Create an instance of {@link FeatureMap.IdentificationRun.ProteinIdentification
     * }
     *
     */
    public FeatureMap.IdentificationRun.ProteinIdentification createFeatureMapIdentificationRunProteinIdentification() {
        return new FeatureMap.IdentificationRun.ProteinIdentification();
    }

    /**
     * Create an instance of {@link FeatureMap.IdentificationRun.SearchParameters
     * }
     *
     */
    public FeatureMap.IdentificationRun.SearchParameters createFeatureMapIdentificationRunSearchParameters() {
        return new FeatureMap.IdentificationRun.SearchParameters();
    }

    /**
     * Create an instance of {@link FeatureMap.DataProcessing }
     *
     */
    public FeatureMap.DataProcessing createFeatureMapDataProcessing() {
        return new FeatureMap.DataProcessing();
    }

    /**
     * Create an instance of {@link FeatureMap.FeatureList }
     *
     */
    public FeatureMap.FeatureList createFeatureMapFeatureList() {
        return new FeatureMap.FeatureList();
    }

    /**
     * Create an instance of {@link FeatureType.Position }
     *
     */
    public FeatureType.Position createFeatureTypePosition() {
        return new FeatureType.Position();
    }

    /**
     * Create an instance of {@link FeatureType.Quality }
     *
     */
    public FeatureType.Quality createFeatureTypeQuality() {
        return new FeatureType.Quality();
    }

    /**
     * Create an instance of {@link FeatureType.Subordinate }
     *
     */
    public FeatureType.Subordinate createFeatureTypeSubordinate() {
        return new FeatureType.Subordinate();
    }

    /**
     * Create an instance of {@link FeatureType.PeptideIdentification.PeptideHit
     * }
     *
     */
    public FeatureType.PeptideIdentification.PeptideHit createFeatureTypePeptideIdentificationPeptideHit() {
        return new FeatureType.PeptideIdentification.PeptideHit();
    }

    /**
     * Create an instance of {@link FeatureType.Convexhull.Pt }
     *
     */
    public FeatureType.Convexhull.Pt createFeatureTypeConvexhullPt() {
        return new FeatureType.Convexhull.Pt();
    }

    /**
     * Create an instance of {@link FeatureType.Convexhull.Hullpoint.Hposition }
     *
     */
    public FeatureType.Convexhull.Hullpoint.Hposition createFeatureTypeConvexhullHullpointHposition() {
        return new FeatureType.Convexhull.Hullpoint.Hposition();
    }

    /**
     * Create an instance of {@link FeatureType.Model.Param }
     *
     */
    public FeatureType.Model.Param createFeatureTypeModelParam() {
        return new FeatureType.Model.Param();
    }

    /**
     * Create an instance of {@link FeatureMap.UnassignedPeptideIdentification.PeptideHit
     * }
     *
     */
    public FeatureMap.UnassignedPeptideIdentification.PeptideHit createFeatureMapUnassignedPeptideIdentificationPeptideHit() {
        return new FeatureMap.UnassignedPeptideIdentification.PeptideHit();
    }

    /**
     * Create an instance of {@link FeatureMap.IdentificationRun.ProteinIdentification.ProteinHit
     * }
     *
     */
    public FeatureMap.IdentificationRun.ProteinIdentification.ProteinHit createFeatureMapIdentificationRunProteinIdentificationProteinHit() {
        return new FeatureMap.IdentificationRun.ProteinIdentification.ProteinHit();
    }

    /**
     * Create an instance of {@link FeatureMap.IdentificationRun.SearchParameters.FixedModification
     * }
     *
     */
    public FeatureMap.IdentificationRun.SearchParameters.FixedModification createFeatureMapIdentificationRunSearchParametersFixedModification() {
        return new FeatureMap.IdentificationRun.SearchParameters.FixedModification();
    }

    /**
     * Create an instance of {@link FeatureMap.IdentificationRun.SearchParameters.VariableModification
     * }
     *
     */
    public FeatureMap.IdentificationRun.SearchParameters.VariableModification createFeatureMapIdentificationRunSearchParametersVariableModification() {
        return new FeatureMap.IdentificationRun.SearchParameters.VariableModification();
    }

    /**
     * Create an instance of {@link FeatureMap.DataProcessing.Software }
     *
     */
    public FeatureMap.DataProcessing.Software createFeatureMapDataProcessingSoftware() {
        return new FeatureMap.DataProcessing.Software();
    }

    /**
     * Create an instance of {@link FeatureMap.DataProcessing.ProcessingAction }
     *
     */
    public FeatureMap.DataProcessing.ProcessingAction createFeatureMapDataProcessingProcessingAction() {
        return new FeatureMap.DataProcessing.ProcessingAction();
    }

    /**
     * Create an instance of {@link FeatureMap.DataProcessing.UserParam }
     *
     */
    public FeatureMap.DataProcessing.UserParam createFeatureMapDataProcessingUserParam() {
        return new FeatureMap.DataProcessing.UserParam();
    }

}
