
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.03.18 at 02:59:01 PM GMT 
//
package uk.ac.liv.pgb.mzqlib.openms.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DigestionEnzyme.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <pre>
 * &lt;simpleType name="DigestionEnzyme"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="pepsin_a"/&gt;
 * &lt;enumeration value="chymotrypsin"/&gt;
 * &lt;enumeration value="proteinase_k"/&gt;
 * &lt;enumeration value="trypsin"/&gt;
 * &lt;enumeration value="no_enzyme"/&gt;
 * &lt;enumeration value="unknown_enzyme"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "DigestionEnzyme")
@XmlEnum
public enum DigestionEnzyme {

    /**
     *
     */
    @XmlEnumValue("pepsin_a")
    PEPSIN_A("pepsin_a"),

    /**
     *
     */
    @XmlEnumValue("chymotrypsin")
    CHYMOTRYPSIN("chymotrypsin"),

    /**
     *
     */
    @XmlEnumValue("proteinase_k")
    PROTEINASE_K("proteinase_k"),

    /**
     *
     */
    @XmlEnumValue("trypsin")
    TRYPSIN("trypsin"),

    /**
     *
     */
    @XmlEnumValue("no_enzyme")
    NO_ENZYME("no_enzyme"),

    /**
     *
     */
    @XmlEnumValue("unknown_enzyme")
    UNKNOWN_ENZYME("unknown_enzyme");

    private final String value;

    DigestionEnzyme(String v) {
        value = v;
    }

    /**
     * Get digestion enzyme from value.
     *
     * @param v value
     *
     * @return digestion enzyme.
     */
    public static DigestionEnzyme fromValue(String v) {
        for (DigestionEnzyme c : DigestionEnzyme.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }

        throw new IllegalArgumentException(v);
    }

    /**
     * Get value.
     *
     * @return value.
     */
    public String value() {
        return value;
    }
}
//~ Formatted by Jindent --- http://www.jindent.com
