//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 04:56:02 PM BST 
//

package uk.ac.liv.pgb.mzqlib.openms.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for featureType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="featureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="position" maxOccurs="2" minOccurs="2">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
 *                 &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="intensity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="quality" maxOccurs="2" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
 *                 &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="overallquality" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="charge" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="model" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="convexhull" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="hullpoint" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hposition" maxOccurs="2" minOccurs="2">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
 *                                     &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="pt" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *                 &lt;attribute name="nr" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="subordinate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="feature" type="{}featureType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PeptideIdentification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PeptideHit" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="aa_before">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="0"/>
 *                                 &lt;maxLength value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="aa_after">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="0"/>
 *                                 &lt;maxLength value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="protein_refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="identification_run_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="score_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="higher_score_better" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="significance_threshold" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="spectrum_reference" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="RT" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="MZ" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "featureType", propOrder = {
    "position",
    "intensity",
    "quality",
    "overallquality",
    "charge",
    "model",
    "convexhull",
    "subordinate",
    "peptideIdentification",
    "userParam"
})
public class FeatureType {

    @XmlElement(required = true)
    protected List<FeatureType.Position> position;
    protected double intensity;
    protected List<FeatureType.Quality> quality;
    protected Double overallquality;
    protected Double charge;
    protected FeatureType.Model model;
    protected List<FeatureType.Convexhull> convexhull;
    protected FeatureType.Subordinate subordinate;
    @XmlElement(name = "PeptideIdentification")
    protected List<FeatureType.PeptideIdentification> peptideIdentification;
    protected List<UserParam> userParam;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the position property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the position
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPosition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureType.Position }
     *
     *
     */
    public List<FeatureType.Position> getPosition() {
        if (position == null) {
            position = new ArrayList<FeatureType.Position>();
        }
        return this.position;
    }

    /**
     * Gets the value of the intensity property.
     *
     */
    public double getIntensity() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     *
     */
    public void setIntensity(double value) {
        this.intensity = value;
    }

    /**
     * Gets the value of the quality property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quality
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuality().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureType.Quality }
     *
     *
     */
    public List<FeatureType.Quality> getQuality() {
        if (quality == null) {
            quality = new ArrayList<FeatureType.Quality>();
        }
        return this.quality;
    }

    /**
     * Gets the value of the overallquality property.
     *
     * @return
     *         possible object is
     *         {@link Double }
     *
     */
    public Double getOverallquality() {
        return overallquality;
    }

    /**
     * Sets the value of the overallquality property.
     *
     * @param value
     *              allowed object is
     *              {@link Double }
     *
     */
    public void setOverallquality(Double value) {
        this.overallquality = value;
    }

    /**
     * Gets the value of the charge property.
     *
     * @return
     *         possible object is
     *         {@link Double }
     *
     */
    public Double getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     *
     * @param value
     *              allowed object is
     *              {@link Double }
     *
     */
    public void setCharge(Double value) {
        this.charge = value;
    }

    /**
     * Gets the value of the model property.
     *
     * @return
     *         possible object is
     *         {@link FeatureType.Model }
     *
     */
    public FeatureType.Model getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     *
     * @param value
     *              allowed object is
     *              {@link FeatureType.Model }
     *
     */
    public void setModel(FeatureType.Model value) {
        this.model = value;
    }

    /**
     * Gets the value of the convexhull property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the convexhull
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConvexhull().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureType.Convexhull }
     *
     *
     */
    public List<FeatureType.Convexhull> getConvexhull() {
        if (convexhull == null) {
            convexhull = new ArrayList<FeatureType.Convexhull>();
        }
        return this.convexhull;
    }

    /**
     * Gets the value of the subordinate property.
     *
     * @return
     *         possible object is
     *         {@link FeatureType.Subordinate }
     *
     */
    public FeatureType.Subordinate getSubordinate() {
        return subordinate;
    }

    /**
     * Sets the value of the subordinate property.
     *
     * @param value
     *              allowed object is
     *              {@link FeatureType.Subordinate }
     *
     */
    public void setSubordinate(FeatureType.Subordinate value) {
        this.subordinate = value;
    }

    /**
     * Gets the value of the peptideIdentification property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the
     * peptideIdentification property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeptideIdentification().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureType.PeptideIdentification }
     *
     *
     */
    public List<FeatureType.PeptideIdentification> getPeptideIdentification() {
        if (peptideIdentification == null) {
            peptideIdentification
                    = new ArrayList<FeatureType.PeptideIdentification>();
        }
        return this.peptideIdentification;
    }

    /**
     * Gets the value of the userParam property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userParam
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserParam().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserParam }
     *
     *
     */
    public List<UserParam> getUserParam() {
        if (userParam == null) {
            userParam = new ArrayList<UserParam>();
        }
        return this.userParam;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *              allowed object is
     *              {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="hullpoint" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hposition" maxOccurs="2" minOccurs="2">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
     *                           &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="pt" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *       &lt;attribute name="nr" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hullpoint",
        "pt"
    })
    public static class Convexhull {

        protected List<FeatureType.Convexhull.Hullpoint> hullpoint;
        protected List<FeatureType.Convexhull.Pt> pt;
        @XmlAttribute(name = "nr")
        @XmlSchemaType(name = "anySimpleType")
        protected String nr;

        /**
         * Gets the value of the hullpoint property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hullpoint
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHullpoint().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureType.Convexhull.Hullpoint }
         *
         *
         */
        public List<FeatureType.Convexhull.Hullpoint> getHullpoint() {
            if (hullpoint == null) {
                hullpoint = new ArrayList<FeatureType.Convexhull.Hullpoint>();
            }
            return this.hullpoint;
        }

        /**
         * Gets the value of the pt property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pt
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPt().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureType.Convexhull.Pt }
         *
         *
         */
        public List<FeatureType.Convexhull.Pt> getPt() {
            if (pt == null) {
                pt = new ArrayList<FeatureType.Convexhull.Pt>();
            }
            return this.pt;
        }

        /**
         * Gets the value of the nr property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getNr() {
            return nr;
        }

        /**
         * Sets the value of the nr property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         *
         */
        public void setNr(String value) {
            this.nr = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hposition" maxOccurs="2" minOccurs="2">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
         *                 &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hposition"
        })
        public static class Hullpoint {

            @XmlElement(required = true)
            protected List<FeatureType.Convexhull.Hullpoint.Hposition> hposition;

            /**
             * Gets the value of the hposition property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the
             * hposition property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHposition().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FeatureType.Convexhull.Hullpoint.Hposition }
             *
             *
             */
            public List<FeatureType.Convexhull.Hullpoint.Hposition> getHposition() {
                if (hposition == null) {
                    hposition
                            = new ArrayList<FeatureType.Convexhull.Hullpoint.Hposition>();
                }
                return this.hposition;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
             *       &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Hposition {

                @XmlValue
                @XmlSchemaType(name = "anySimpleType")
                protected double value;
                @XmlAttribute(name = "dim", required = true)
                @XmlSchemaType(name = "anySimpleType")
                protected String dim;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *         possible object is
                 *         {@link Object }
                 *
                 */
                public double getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *              allowed object is
                 *              {@link Object }
                 *
                 */
                public void setValue(double value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the dim property.
                 *
                 * @return
                 *         possible object is
                 *         {@link String }
                 *
                 */
                public String getDim() {
                    return dim;
                }

                /**
                 * Sets the value of the dim property.
                 *
                 * @param value
                 *              allowed object is
                 *              {@link String }
                 *
                 */
                public void setDim(String value) {
                    this.dim = value;
                }

            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Pt {

            @XmlAttribute(name = "x", required = true)
            protected double x;
            @XmlAttribute(name = "y", required = true)
            protected double y;

            /**
             * Gets the value of the x property.
             *
             */
            public double getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             *
             */
            public void setX(double value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             *
             */
            public double getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             *
             */
            public void setY(double value) {
                this.y = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "param"
    })
    public static class Model {

        protected List<FeatureType.Model.Param> param;
        @XmlAttribute(name = "name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String name;

        /**
         * Gets the value of the param property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the param
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParam().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureType.Model.Param }
         *
         *
         */
        public List<FeatureType.Model.Param> getParam() {
            if (param == null) {
                param = new ArrayList<FeatureType.Model.Param>();
            }
            return this.param;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Param {

            @XmlAttribute(name = "name", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String name;
            @XmlAttribute(name = "value", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String value;

            /**
             * Gets the value of the name property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value
             *              allowed object is
             *              {@link String }
             *
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *              allowed object is
             *              {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PeptideHit" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="aa_before">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="0"/>
     *                       &lt;maxLength value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="aa_after">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="0"/>
     *                       &lt;maxLength value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="protein_refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="identification_run_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *       &lt;attribute name="score_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="higher_score_better" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="significance_threshold" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="spectrum_reference" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="RT" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="MZ" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "peptideHit",
        "userParam"
    })
    public static class PeptideIdentification {

        @XmlElement(name = "PeptideHit")
        protected List<FeatureType.PeptideIdentification.PeptideHit> peptideHit;
        protected List<UserParam> userParam;
        @XmlAttribute(name = "identification_run_ref", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object identificationRunRef;
        @XmlAttribute(name = "score_type", required = true)
        protected String scoreType;
        @XmlAttribute(name = "higher_score_better", required = true)
        protected boolean higherScoreBetter;
        @XmlAttribute(name = "significance_threshold")
        protected Float significanceThreshold;
        @XmlAttribute(name = "spectrum_reference")
        @XmlSchemaType(name = "unsignedInt")
        protected Long spectrumReference;
        @XmlAttribute(name = "RT")
        protected Float rt;
        @XmlAttribute(name = "MZ")
        protected Float mz;

        /**
         * Gets the value of the peptideHit property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the peptideHit
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPeptideHit().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureType.PeptideIdentification.PeptideHit }
         *
         *
         */
        public List<FeatureType.PeptideIdentification.PeptideHit> getPeptideHit() {
            if (peptideHit == null) {
                peptideHit
                        = new ArrayList<FeatureType.PeptideIdentification.PeptideHit>();
            }
            return this.peptideHit;
        }

        /**
         * Gets the value of the userParam property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userParam
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserParam().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserParam }
         *
         *
         */
        public List<UserParam> getUserParam() {
            if (userParam == null) {
                userParam = new ArrayList<UserParam>();
            }
            return this.userParam;
        }

        /**
         * Gets the value of the identificationRunRef property.
         *
         * @return
         *         possible object is
         *         {@link Object }
         *
         */
        public Object getIdentificationRunRef() {
            return identificationRunRef;
        }

        /**
         * Sets the value of the identificationRunRef property.
         *
         * @param value
         *              allowed object is
         *              {@link Object }
         *
         */
        public void setIdentificationRunRef(Object value) {
            this.identificationRunRef = value;
        }

        /**
         * Gets the value of the scoreType property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getScoreType() {
            return scoreType;
        }

        /**
         * Sets the value of the scoreType property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         *
         */
        public void setScoreType(String value) {
            this.scoreType = value;
        }

        /**
         * Gets the value of the higherScoreBetter property.
         *
         */
        public boolean isHigherScoreBetter() {
            return higherScoreBetter;
        }

        /**
         * Sets the value of the higherScoreBetter property.
         *
         */
        public void setHigherScoreBetter(boolean value) {
            this.higherScoreBetter = value;
        }

        /**
         * Gets the value of the significanceThreshold property.
         *
         * @return
         *         possible object is
         *         {@link Float }
         *
         */
        public Float getSignificanceThreshold() {
            return significanceThreshold;
        }

        /**
         * Sets the value of the significanceThreshold property.
         *
         * @param value
         *              allowed object is
         *              {@link Float }
         *
         */
        public void setSignificanceThreshold(Float value) {
            this.significanceThreshold = value;
        }

        /**
         * Gets the value of the spectrumReference property.
         *
         * @return
         *         possible object is
         *         {@link Long }
         *
         */
        public Long getSpectrumReference() {
            return spectrumReference;
        }

        /**
         * Sets the value of the spectrumReference property.
         *
         * @param value
         *              allowed object is
         *              {@link Long }
         *
         */
        public void setSpectrumReference(Long value) {
            this.spectrumReference = value;
        }

        /**
         * Gets the value of the rt property.
         *
         * @return
         *         possible object is
         *         {@link Float }
         *
         */
        public Float getRT() {
            return rt;
        }

        /**
         * Sets the value of the rt property.
         *
         * @param value
         *              allowed object is
         *              {@link Float }
         *
         */
        public void setRT(Float value) {
            this.rt = value;
        }

        /**
         * Gets the value of the mz property.
         *
         * @return
         *         possible object is
         *         {@link Float }
         *
         */
        public Float getMZ() {
            return mz;
        }

        /**
         * Sets the value of the mz property.
         *
         * @param value
         *              allowed object is
         *              {@link Float }
         *
         */
        public void setMZ(Float value) {
            this.mz = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="aa_before">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="0"/>
         *             &lt;maxLength value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="aa_after">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="0"/>
         *             &lt;maxLength value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="protein_refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "userParam"
        })
        public static class PeptideHit {

            protected List<UserParam> userParam;
            @XmlAttribute(name = "sequence", required = true)
            protected String sequence;
            @XmlAttribute(name = "charge", required = true)
            protected BigInteger charge;
            @XmlAttribute(name = "score", required = true)
            protected float score;
            @XmlAttribute(name = "aa_before")
            protected String aaBefore;
            @XmlAttribute(name = "aa_after")
            protected String aaAfter;
            @XmlAttribute(name = "protein_refs")
            @XmlIDREF
            @XmlSchemaType(name = "IDREFS")
            protected List<Object> proteinRefs;

            /**
             * Gets the value of the userParam property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the
             * userParam property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUserParam().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link UserParam }
             *
             *
             */
            public List<UserParam> getUserParam() {
                if (userParam == null) {
                    userParam = new ArrayList<UserParam>();
                }
                return this.userParam;
            }

            /**
             * Gets the value of the sequence property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getSequence() {
                return sequence;
            }

            /**
             * Sets the value of the sequence property.
             *
             * @param value
             *              allowed object is
             *              {@link String }
             *
             */
            public void setSequence(String value) {
                this.sequence = value;
            }

            /**
             * Gets the value of the charge property.
             *
             * @return
             *         possible object is
             *         {@link BigInteger }
             *
             */
            public BigInteger getCharge() {
                return charge;
            }

            /**
             * Sets the value of the charge property.
             *
             * @param value
             *              allowed object is
             *              {@link BigInteger }
             *
             */
            public void setCharge(BigInteger value) {
                this.charge = value;
            }

            /**
             * Gets the value of the score property.
             *
             */
            public float getScore() {
                return score;
            }

            /**
             * Sets the value of the score property.
             *
             */
            public void setScore(float value) {
                this.score = value;
            }

            /**
             * Gets the value of the aaBefore property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getAaBefore() {
                return aaBefore;
            }

            /**
             * Sets the value of the aaBefore property.
             *
             * @param value
             *              allowed object is
             *              {@link String }
             *
             */
            public void setAaBefore(String value) {
                this.aaBefore = value;
            }

            /**
             * Gets the value of the aaAfter property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getAaAfter() {
                return aaAfter;
            }

            /**
             * Sets the value of the aaAfter property.
             *
             * @param value
             *              allowed object is
             *              {@link String }
             *
             */
            public void setAaAfter(String value) {
                this.aaAfter = value;
            }

            /**
             * Gets the value of the proteinRefs property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the
             * proteinRefs property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProteinRefs().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Object }
             *
             *
             */
            public List<Object> getProteinRefs() {
                if (proteinRefs == null) {
                    proteinRefs = new ArrayList<Object>();
                }
                return this.proteinRefs;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
     *       &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Position {

        @XmlValue
        @XmlSchemaType(name = "anySimpleType")
        protected double value;
        @XmlAttribute(name = "dim", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String dim;

        /**
         * Gets the value of the value property.
         *
         * @return
         *         possible object is
         *         {@link Object }
         *
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *              allowed object is
         *              {@link Object }
         *
         */
        public void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the dim property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getDim() {
            return dim;
        }

        /**
         * Sets the value of the dim property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         *
         */
        public void setDim(String value) {
            this.dim = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
     *       &lt;attribute name="dim" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Quality {

        @XmlValue
        @XmlSchemaType(name = "anySimpleType")
        protected double value;
        @XmlAttribute(name = "dim", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String dim;

        /**
         * Gets the value of the value property.
         *
         * @return
         *         possible object is
         *         {@link Object }
         *
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *              allowed object is
         *              {@link Object }
         *
         */
        public void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the dim property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getDim() {
            return dim;
        }

        /**
         * Sets the value of the dim property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         *
         */
        public void setDim(String value) {
            this.dim = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="feature" type="{}featureType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "feature"
    })
    public static class Subordinate {

        protected List<FeatureType> feature;

        /**
         * Gets the value of the feature property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feature
         * property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeature().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureType }
         *
         *
         */
        public List<FeatureType> getFeature() {
            if (feature == null) {
                feature = new ArrayList<FeatureType>();
            }
            return this.feature;
        }

    }

}
