
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.03.18 at 02:59:01 PM GMT 
//
package uk.ac.liv.pgb.mzqlib.openms.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MassType.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <pre>
 * &lt;simpleType name="MassType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="average"/&gt;
 * &lt;enumeration value="monoisotopic"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "MassType")
@XmlEnum
public enum MassType {

    /**
     *
     */
    @XmlEnumValue("average")
    AVERAGE("average"),

    /**
     *
     */
    @XmlEnumValue("monoisotopic")
    MONOISOTOPIC("monoisotopic");

    private final String value;

    MassType(String v) {
        value = v;
    }

    /**
     * Get mass type by value.
     *
     * @param v value.
     *
     * @return mass type.
     */
    public static MassType fromValue(String v) {
        for (MassType c : MassType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }

        throw new IllegalArgumentException(v);
    }

    /**
     * Get mass type value.
     *
     * @return value.
     */
    public String value() {
        return value;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
