//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 02:59:01 PM GMT 
//

package uk.ac.liv.pgb.mzqlib.openms.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for UserParamType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UserParamType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="int"/&gt;
 * &lt;enumeration value="float"/&gt;
 * &lt;enumeration value="string"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "UserParamType")
@XmlEnum
public enum UserParamType {

    /**
     *
     */
    @XmlEnumValue("int")
    INT("int"),

    /**
     *
     */
    @XmlEnumValue("float")
    FLOAT("float"),

    /**
     *
     */
    @XmlEnumValue("string")
    STRING("string");
    private final String value;

    UserParamType(String v) {
        value = v;
    }

    /**
     * Get UserParam type value.
     *
     * @return value.
     */
    public String value() {
        return value;
    }

    /**
     * Get UserParam type from value.
     *
     * @param v value.
     *
     * @return UserParam type.
     */
    public static UserParamType fromValue(String v) {
        for (UserParamType c : UserParamType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
